server:
  port: 7010

logging:
  level:
    org:
      springframework:
        transaction: DEBUG
      hibernate:
        type: trace
    project:
      user:
        UserClient: DEBUG
spring:
  application:
    name: kotlin-examples
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: none